### PR TITLE
Some minor typos and fixes

### PR DESCRIPTION
**Pull request by shrutivanw**
@susanev This PR includes a few minor typos, fixes to make spacing consistent and minor bug fixes. Could you help with review and merge?
P.S: I had fun learning from the JSL content and videos! :-)

### CODE REVIEW

**Comment by susanev** [comment]
on boolean_expressions.md, I'm a bit worried about the phrase, "the right way"; this seems loaded and similar to a judgment statement. maybe "to", instead of "you"; not sure what you were going for here.

**Comment by susanev** [comment]
@shrutivanw thanks for the rest of the fixes; looks like I need to learn how to properly use "it's" and "its" .. 😆

**Comment by shrutivanw** [comment]
Good point on boolean_expressions.md! How about "It's important to understand how to combine relational operators with logical operators."

**Comment by susanev** [comment]
sounds good

**Comment by shrutivanw** [comment]
Thank you, @susanev!

**Pull request merged**
